### ISSUE TITLE
NoSiteContext

### ISSUE THREAD

**Issue by joshdinsdale** [hobbyquaker/unifi2mqtt#12]
Hi All

I am getting an issue where i am getting a 'NoSiteContext' error message. I only have a single site, so it should be 'default', i have tried specifying this manually and using the default option, but its the same. Full debug below:

`2018-12-19 09:17:18.366 <info>  unifi2mqtt 1.1.0 starting
2018-12-19 09:17:18.374 <info>  mqtt trying to connect mqtt://192.168.7.12
2018-12-19 09:17:18.485 <info>  trying to connect https://127.0.0.1:8443
2018-12-19 09:17:18.803 <info>  mqtt connected mqtt://192.168.7.12
2018-12-19 09:17:18.804 <debug> mqtt > unifi/connected 1
2018-12-19 09:17:18.807 <info>  mqtt subscribe unifi/set/#
2018-12-19 09:17:18.809 <info>  mqtt subscribe unifi/status/wifi/+/client/+
2018-12-19 09:17:19.184 <debug> mqtt > unifi/connected 2
2018-12-19 09:17:19.185 <info>  unifi connected
2018-12-19 09:17:19.186 <debug> unifi > rest/wlanconf
Unhandled rejection StatusCodeError: 401 - {"data":[],"meta":{"msg":"api.err.NoSiteContext","rc":"error"}}
    at new StatusCodeError (/usr/local/lib/node_modules/unifi2mqtt/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/usr/local/lib/node_modules/unifi2mqtt/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/unifi2mqtt/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/usr/local/lib/node_modules/unifi2mqtt/node_modules/request/request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/unifi2mqtt/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:189:13)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/unifi2mqtt/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:277:13)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)

`

Any help would be much appreciated! :)

**Comment by hobbyquaker** [comment]
`NoSiteContext` comes from the controller when the site is addressed by its display name. `--site` expects the site **id** — the part after `/site/` in the controller URL (`default` for the first site). 2.0.0 documents that in the option table and also supports UniFi OS consoles (UDM/UDR/CK G2) with `/proxy/network` paths.

Closing — the 1.x code base this refers to is gone with 2.0.0; if it still bites on 2.0.0, please open a new issue with the debug log (`--verbosity debug`).
