### ISSUE TITLE
getting syntax error

### ISSUE THREAD

**Issue by stoneobscurity** [hobbyquaker/unifi2mqtt#13]
root@vmUniFi:/home/stone/node_modules/unifi2mqtt# unifi2mqtt -a 127.0.0.1 -p 8443 -c username -s sekret -w obscurity -k -u mqtt://username:sekret@10.x.x.x:1883
/usr/local/lib/node_modules/unifi2mqtt/index.js:16
let mqttConnected;
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by hobbyquaker** [comment]
That is Node 4 (`let` outside strict mode); 1.x needed Node 6+. 2.0.0 requires Node 20 or newer (`node --version`).

Closing — the 1.x code base this refers to is gone with 2.0.0; if it still bites on 2.0.0, please open a new issue with the debug log (`--verbosity debug`).
