### ISSUE TITLE
Got error if using hint from Dockerfile to pass arguments

### ISSUE THREAD

**Issue by Boldie** [hobbyquaker/unifi2mqtt#17]
If one uses the hint from the Dockerfile to pass arguments, the script exits with an error:

```
$ docker run --rm 118f2b38c69f -e "unifi-password=supersekrit"
[eval]:1
unifi-password=supersekrit
^^^^^^^^^^^^^^

SyntaxError: Invalid left-hand side in assignment
    at new Script (vm.js:84:7)
    at createScript (vm.js:258:10)
    at Object.runInThisContext (vm.js:306:10)
    at Object.<anonymous> ([eval]-wrapper:9:26)
    at Module._compile (internal/modules/cjs/loader.js:1121:30)
    at evalScript (internal/process/execution.js:80:25)
    at internal/main/eval_string.js:23:3
```

**Comment by hobbyquaker** [comment]
2.0.0 configures everything through environment variables (`UNIFI2MQTT_CONTROLLER`, `UNIFI2MQTT_USERNAME`, `UNIFI2MQTT_PASSWORD`, …) or CLI flags appended after the image name — `docker run … ghcr.io/hobbyquaker/unifi2mqtt -c https://udm -u user -p pw`. The `-e key=value` hint from the old Dockerfile is gone.

Closing — the 1.x code base this refers to is gone with 2.0.0; if it still bites on 2.0.0, please open a new issue with the debug log (`--verbosity debug`).
